# Generated by Django 5.1 on 2025-08-07 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('poster_name', models.CharField(max_length=255)),
                ('poster_image', models.ImageField(upload_to='posters/')),
                ('state', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id_specification', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_name', models.CharField(max_length=45, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45, verbose_name='Category')),
                ('category_description', models.CharField(max_length=255, verbose_name='Description')),
                ('image_category', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagen de categorias')),
                ('demanded', models.BooleanField(blank=True, null=True, verbose_name='demanded state')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalogoHome.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='tecnology/', verbose_name='Imagen de productos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogoHome.category')),
            ],
        ),
    ]
