# Generated by Django 5.1 on 2025-06-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Categoria')),
                ('category_description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id_specification', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_name', models.CharField(max_length=45, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.UUIDField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('price', models.IntegerField(max_length=45, verbose_name='Precio')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('image_product', models.ImageField(null=True, upload_to='', verbose_name='Imagen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogoHome.category')),
            ],
        ),
    ]
