# Generated by Django 5.1 on 2025-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(null=True, upload_to='tecnologia/', verbose_name='Imagen'),
        ),
    ]
