# Generated by Django 5.1 on 2025-06-11 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0004_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
