# Generated by Django 5.1 on 2025-06-17 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0005_alter_category_id_category_alter_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalogoHome.category', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=45, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='specification_name',
            field=models.CharField(max_length=45, verbose_name='name'),
        ),
    ]
