# Generated by Django 5.1 on 2025-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0006_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_category',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='imagen de categorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(null=True, upload_to='tecnology/', verbose_name='Imagen de productos'),
        ),
    ]
