# Generated by Django 5.1 on 2025-06-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0007_category_image_category_alter_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='tecnology/', verbose_name='Imagen de productos'),
        ),
    ]
