# Generated by Django 5.1 on 2025-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0008_alter_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagen de categorias'),
        ),
    ]
