# Generated by Django 5.1 on 2025-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoHome', '0009_alter_category_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='demanded',
            field=models.BooleanField(blank=True, null=True, verbose_name='demanded state'),
        ),
    ]
